name: Painter CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/painterTest.cpp'
jobs:
  simpleAI_job:
    runs-on: ubuntu-latest
    name: painter Job
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: sudo apt-get update
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure privelige
        run: chmod +x configure
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make test
        run: make test
